### ISSUE TITLE
Broken in streamlit-1.34

### ISSUE THREAD

**Issue by kaizen63** [NathanChen198/streamlit-rsa-auth-ui#1]
Him
not sure if this is a streamlit issue or an issue in streamlit-rsa-auth-ui.
Since streamlit 1.34 this module is broken.

Sampe code:

```python
from streamlit_rsa_auth_ui import Encryptor

encryptor = Encryptor.generateNew(2048)
encryptor.save("./.rsa", "authkey")
```
Stack trace:
Traceback (most recent call last):
  File "D:\DevOps\cloud_coe\sre-niq-app-metadata-ui\app\generateKeys.py", line 1, in <module>
    from streamlit_rsa_auth_ui import Encryptor
  File "C:\Users\poitschkka01\AppData\Local\pypoetry\Cache\virtualenvs\sre-niq-app-metadata-ui-KVFfTU9t-py3.11\Lib\site-packages\streamlit_rsa_auth_ui\__init__.py", line 11, in <module>
    from .form import Object, authUI
  File "C:\Users\poitschkka01\AppData\Local\pypoetry\Cache\virtualenvs\sre-niq-app-metadata-ui-KVFfTU9t-py3.11\Lib\site-packages\streamlit_rsa_auth_ui\form.py", line 21, in <module>
    _componentFunc = components.declare_component("rsa_auth_ui", path=build_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poitschkka01\AppData\Local\pypoetry\Cache\virtualenvs\sre-niq-app-metadata-ui-KVFfTU9t-py3.11\Lib\site-packages\streamlit\components\v1\component_registry.py", line 87, in declare_component
    get_instance().component_registry.register_component(component)
    ^^^^^^^^^^^^^^
  File "C:\Users\poitschkka01\AppData\Local\pypoetry\Cache\virtualenvs\sre-niq-app-metadata-ui-KVFfTU9t-py3.11\Lib\site-packages\streamlit\runtime\__init__.py", line 28, in get_instance
    return Runtime.instance()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\poitschkka01\AppData\Local\pypoetry\Cache\virtualenvs\sre-niq-app-metadata-ui-KVFfTU9t-py3.11\Lib\site-packages\streamlit\runtime\runtime.py", line 163, in instance
    raise RuntimeError("Runtime hasn't been created!")
RuntimeError: Runtime hasn't been created!

**Comment by kaizen63** [comment]
Looks like this is a streamlit issue: https://github.com/streamlit/streamlit/issues/8606
